- name: Playbook that calls git_plan role
  hosts: localhost
  roles:
    - role: cloud.terraform.git_plan
      project_path: 'my_project_directory'
      mapping_variables:
        host_lists: terraform_var_host_list
        name: terraform_var_name
        ip: terraform_var_ip
        user: terraform_var_user
        group: terraform_var_group