---
- name: Apply Stashed Terraform Plan
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    tf_environment: "{{ tf_environment | default('dev') }}"
    tf_backend_map:
      dev:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/dev/terraform.tfstate
      stage:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/stage/terraform.tfstate
      prod:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/prod/terraform.tfstate
  
  collections:
    - cloud.terraform

  tasks:
    - name: Clone github repo
      ansible.builtin.git:
        repo: "{{ git_url_tf }}"
        dest: "urban"
        version: "main"
        force: true

    - name: Load a terraform plan file from variable
      cloud.terraform.plan_stash:
        path: urban/terraform/tfplan
        binary_data: "{{ stashed_plan }}"
        state: load
      #no_log: true

    - name: Apply the stashed Terraform plan from a variable
      cloud.terraform.terraform:
        project_path: "urban/terraform"
        plan_file: tfplan
        force_init: yes
        init_reconfigure: yes
        state: present
        backend_config:
          region: "{{ tf_backend_map[tf_environment].region }}"
          bucket: "{{ tf_backend_map[tf_environment].bucket }}"
          key: "{{ tf_backend_map[tf_environment].key }}"
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output
