---
- name: Apply Stashed Terraform Plan
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars.yml
  vars:
    - terraform_plan: "{{ terraform_plan }}"


  tasks:
    - name: Load a terraform plan file from variable
      cloud.terraform.plan_stash:
        path: tfplan
        var_name: "{{ terraform_plan }}"
        state: load
      #no_log: true

    - name: Apply the stashed Terraform plan from a variable
      cloud.terraform.terraform:
        plan_file: tfplan
        state: present
        backend_config:
          region: "{{ region }}"
          bucket: "{{ s3_bucket_name }}"
          key: "terraform.tfstate"
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output