---
- name: Apply Stashed Terraform Plan
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars.yml

  tasks:
    - name: Clone github repo
      ansible.builtin.git:
        repo: "https://github.com/r3dact3d/urban-terraform"
        dest: "urban"
        version: "main"
        force: true

    - name: Load a terraform plan file from variable
      cloud.terraform.plan_stash:
        path: urban/terraform/tfplan
        binary_data: "{{ stashed_plan }}"
        state: load
      #no_log: true

    - name: Apply the stashed Terraform plan from a variable
      cloud.terraform.terraform:
        project_path: "urban/terraform"
        plan_file: tfplan
        state: present
        backend_config:
          region: "{{ region }}"
          bucket: "{{ s3_bucket_name }}"
          key: "terraform.tfstate"
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output