---
- name: Apply Stashed Terraform Plan
  hosts: localhost
  connection: local
  gather_facts: no
  
  collections:
    - cloud.terraform

  tasks:
    - name: Clone github repo
      ansible.builtin.git:
        repo: "{{ git_url_tf }}"
        dest: "urban"
        version: "main"
        force: true

    - name: Load a terraform plan file from variable
      cloud.terraform.plan_stash:
        path: urban/terraform/tfplan
        binary_data: "{{ stashed_plan }}"
        state: load
      #no_log: true

    - name: Apply the stashed Terraform plan from a variable
      cloud.terraform.terraform:
        project_path: "urban/terraform"
        plan_file: tfplan
        force_init: yes
        init_reconfigure: yes
        state: present
        backend_config:
          region: "{{ tf_region }}"
          bucket: "{{ tf_s3_bucket }}"
          key: "random.tfstate"
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output