---
- name: Terraform Init and Plan
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars.yml
  collections:
    - cloud.terraform
    - amazon.aws

  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ s3_bucket_name }}"
      register: s3_bucket_info

    - name: Create S3 bucket if it doesn't exist
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: present
        region: "{{ region }}"
        public_access:
          block_public_acls: true
          ignore_public_acls: true
      when: s3_bucket_info.buckets | default([]) | length == 0
    
    - name: Initialize Terraform
      community.general.terraform:
        project_path: "terraform/"
        state: present
        force_init: true
        backend_config:
          region: "{{ region }}"
          bucket: "{{ s3_bucket_name }}"
          key: "terraform.tfstate"
      check_mode: yes
      register: terraform_output
    
    - name: Show Terraform output
      debug:
        var: terraform_output
