---
- name: Terraform Init and Plan
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    tf_environment: "{{ tf_environment | default('dev') }}"
    tf_backend_map:
      dev:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/dev/terraform.tfstate
      stage:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/stage/terraform.tfstate
      prod:
        region: us-east-1
        bucket: brthomps-tfstate-use1
        key: aap-on-aws/prod/terraform.tfstate

  collections:
    - cloud.terraform
    - amazon.aws

  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ tf_backend_map[tf_environment].bucket }}"
      register: s3_bucket_info

    - name: Create S3 bucket if it doesn't exist
      amazon.aws.s3_bucket:
        name: "{{ tf_backend_map[tf_environment].bucket }}"
        state: present
        region: "{{ tf_backend_map[tf_environment].region }}"
        public_access:
          block_public_acls: true
          ignore_public_acls: true
      when: s3_bucket_info.buckets | default([]) | length == 0
  
    - name: Clone github repo
      ansible.builtin.git:
        repo: "{{ git_url_tf }}"
        dest: "urban"
        version: "main"
        force: true

    - name: Initialize Terraform
      cloud.terraform.terraform:
        project_path: "urban/terraform/"
        state: present
        force_init: yes
        init_reconfigure: yes
        plan_file: "theplan"
        backend_config:
          region: "{{ tf_backend_map[tf_environment].region }}"
          bucket: "{{ tf_backend_map[tf_environment].bucket }}"
          key: "{{ tf_backend_map[tf_environment].key }}"
      check_mode: yes
      register: terraform_output

    - name: Show Terraform output
      debug:
        var: terraform_output

    - name: Stash Terraform plan
      cloud.terraform.plan_stash:
        path: "urban/terraform/theplan"
        var_name: stashed_plan
        state: stash
      #no_log: true
      register: registered_plan

    - name: Show Terraform output
      debug:
        var: registered_plan
...